# Generated by Django 3.1.1 on 2020-09-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'draft'), ('99', 'published')], db_index=True, default='1', max_length=2, verbose_name='status')),
                ('publication_start', models.DateTimeField(blank=True, null=True, verbose_name='publication start')),
                ('publication_end', models.DateTimeField(blank=True, null=True, verbose_name='publication end')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-publication_start'],
                'get_latest_by': 'publication_start',
                'abstract': False,
            },
        ),
    ]
